spring:

  application:
    name: file-handler

  datasource:
    url: jdbc:postgresql://localhost:5432/files
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.yml
    default-schema: public

sorting:
  field: creationDate

server:
  port: 8081


